list: $/realhero/content/models/type/columns.yaml
modelClass: RealHero\Content\Models\Type
title: Types
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'realhero/content/types/update/:id'
