list: $/realhero/content/models/article/columns.yaml
modelClass: RealHero\Content\Models\Article
title: Articles
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'realhero/content/articles/update/:id'
